// Package project provides a zero-dependency, file-backed store for long-lived
// project context. Each project is a folder on disk containing a metadata
// JSON file and a free-form context.md (markdown notes that the agent can
// read/write to carry knowledge across sessions).
//
// This mirrors the existing memory/ JSON-store pattern so the whole app stays
// "standard library only" — no external database required.
package project

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/darkcode/internal/strutil"
)

// Project is a single tracked project and its long-lived context.
type Project struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description,omitempty"`
	Path        string    `json:"path,omitempty"` // working directory for this project
	Tags        []string  `json:"tags,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	LastOpened  time.Time `json:"last_opened"`

	// Context is the markdown context/notes. It is loaded on demand by
	// GetWithContext / GetContext rather than by List (which can be large).
	// The `context,omitempty` tag lets it appear in API JSON responses; it is
	// explicitly cleared in saveMetaLocked so it is never duplicated into the
	// on-disk project.json (it lives in context.md instead).
	Context  string `json:"context,omitempty"`
	Plan     string `json:"plan,omitempty"`
	Workflow string `json:"workflow,omitempty"`

	// Summary is a compressed briefing of the project context (generated by
	// the configured compressor model). It is loaded on demand like Context,
	// and is injected into the chat prompt INSTEAD of the raw context.md when
	// available, so reopening a project after a long gap gives the LLM a
	// compact advance briefing rather than up to 1 MiB of raw session log.
	Summary string `json:"summary,omitempty"`

	// SummaryLen is the len(context) recorded when Summary was last generated.
	// It drives staleness detection: the server recompresses only after the
	// context has grown meaningfully (see summaryRegrowth in server.go). It IS
	// persisted in project.json (it is small and metadata-like).
	SummaryLen int `json:"summary_len,omitempty"`
}

// maxContextBytes caps a single project's context.md to avoid unbounded growth.
const maxContextBytes = 1 << 20 // 1 MiB

// maxSummaryBytes caps a single project's compressed summary. Summaries are
// meant to be compact briefings, so the cap is far smaller than context.md.
const maxSummaryBytes = 64 * 1024 // 64 KiB

// recentActivityTail is how many bytes of the raw context.md are appended
// after the compressed summary as the "Recent Activity" section. Bounded so
// the prompt stays small even for very large projects.
const recentActivityTail = 8 * 1024 // 8 KiB

// Store is a thread-safe, file-backed collection of projects.
type Store struct {
	mu   sync.RWMutex
	root string
}

// NewStore creates (or opens) a project store rooted at the given directory.
func NewStore(root string) (*Store, error) {
	if err := os.MkdirAll(root, 0755); err != nil {
		return nil, fmt.Errorf("create projects dir: %w", err)
	}
	return &Store{root: root}, nil
}

// Root returns the on-disk root directory.
func (s *Store) Root() string { return s.root }

// Create registers a new project and returns it.
func (s *Store) Create(name, description, path string, tags []string) (*Project, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return nil, fmt.Errorf("project name is required")
	}
	now := time.Now()
	p := &Project{
		ID:          newID(name),
		Name:        name,
		Description: strings.TrimSpace(description),
		Path:        strings.TrimSpace(path),
		Tags:        cleanTags(tags),
		CreatedAt:   now,
		UpdatedAt:   now,
		LastOpened:  now,
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	dir := s.dir(p.ID)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return nil, err
	}
	if err := s.saveMetaLocked(p); err != nil {
		return nil, err
	}
	return p, nil
}

// Get returns a project's metadata (without the context body).
func (s *Store) Get(id string) (*Project, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.loadMetaLocked(id)
}

// GetWithContext returns a project with its context.md body loaded.
func (s *Store) GetWithContext(id string) (*Project, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	p, err := s.loadMetaLocked(id)
	if err != nil {
		return nil, err
	}
	ctx, err := s.loadContextLocked(id)
	if err != nil {
		return nil, err
	}
	p.Context = ctx
	// Also load the compressed summary so the GUI / API can surface it and so
	// the server can decide whether to inject the summary vs raw context.
	if sm, _ := s.loadSummaryLocked(id); sm != "" {
		p.Summary = sm
	}
	return p, nil
}

// List returns all projects (metadata only), most-recently-opened first.
func (s *Store) List() []*Project {
	s.mu.RLock()
	defer s.mu.RUnlock()
	entries, err := os.ReadDir(s.root)
	if err != nil {
		return nil
	}
	var out []*Project
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		p, err := s.loadMetaLocked(e.Name())
		if err != nil {
			continue
		}
		out = append(out, p)
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].LastOpened.After(out[j].LastOpened)
	})
	return out
}

// Update applies partial updates to a project's metadata.
func (s *Store) Update(id string, name, description, path *string, tags []string) (*Project, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	p, err := s.loadMetaLocked(id)
	if err != nil {
		return nil, err
	}
	if name != nil {
		v := strings.TrimSpace(*name)
		if v == "" {
			return nil, fmt.Errorf("project name cannot be empty")
		}
		p.Name = v
	}
	if description != nil {
		p.Description = strings.TrimSpace(*description)
	}
	if path != nil {
		p.Path = strings.TrimSpace(*path)
	}
	if tags != nil {
		p.Tags = cleanTags(tags)
	}
	p.UpdatedAt = time.Now()
	if err := s.saveMetaLocked(p); err != nil {
		return nil, err
	}
	return p, nil
}

// SetContext writes the project's context.md (the long-lived notes/knowledge).
func (s *Store) SetContext(id, context string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, err := s.loadMetaLocked(id); err != nil {
		return err
	}
	if len(context) > maxContextBytes {
		context = context[:maxContextBytes]
	}
	return os.WriteFile(s.contextPath(id), []byte(context), 0644)
}

// SetSummary writes the project's compressed context summary (summary.md)
// and records the context length at generation time (SummaryLen) in the
// metadata so the server can detect staleness and recompress only after
// meaningful growth. ctxLen is len(context) at the moment of compression.
func (s *Store) SetSummary(id, summary string, ctxLen int) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	p, err := s.loadMetaLocked(id)
	if err != nil {
		return err
	}
	if len(summary) > maxSummaryBytes {
		summary = summary[:maxSummaryBytes]
	}
	if err := os.WriteFile(s.summaryPath(id), []byte(summary), 0644); err != nil {
		return err
	}
	p.SummaryLen = ctxLen
	return s.saveMetaLocked(p)
}

// GetSummary reads the project's compressed summary body. Returns "" (no
// error) when no summary has been generated yet.
func (s *Store) GetSummary(id string) (string, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.loadSummaryLocked(id)
}

// SummaryLen returns the context length recorded when the summary was last
// generated (0 if never generated). Used for staleness detection.
func (s *Store) SummaryLen(id string) (int, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	p, err := s.loadMetaLocked(id)
	if err != nil {
		return 0, err
	}
	return p.SummaryLen, nil
}

// GetContext reads the project's context.md body.
func (s *Store) GetContext(id string) (string, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.loadContextLocked(id)
}

// AppendRawContext appends text to the hidden context_raw.md file. This acts as
// a full history backup of all chat logs since context.md is heavily rewritten and
// compressed.
func (s *Store) AppendRawContext(id, appendText string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, err := s.loadMetaLocked(id); err != nil {
		return err
	}
	f, err := os.OpenFile(s.rawContextPath(id), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(appendText + "\n")
	return err
}

// maxContextInjectBytes caps how much of context.md BuildContextQuery injects
// into a single query. context.md itself can be up to maxContextBytes (1
// MiB, SetContext's cap) — "kept small via automatic and explicit rewriting"
// is a goal LLM compression aims for, not something enforced at read time, so
// this was the one injection path in the codebase with no cap at all: a
// project that hadn't been recompressed recently could glue the better part
// of a megabyte onto every single task query. Matches the order of magnitude
// orchestrator.maxPlanInjectBytes uses for the same kind of injection.
const maxContextInjectBytes = 8192

// BuildContextQuery assembles the project-context prefix prepended to the
// user's task. It strictly injects the current context.md, which is kept small
// via automatic and explicit rewriting using the local LLM model.
func (s *Store) BuildContextQuery(id, task string) string {
	rawContext, err := s.GetContext(id)
	rawContext = strings.TrimSpace(rawContext)
	if err != nil || rawContext == "" {
		return task
	}
	rawContext = strutil.TruncateMid(rawContext, maxContextInjectBytes)
	return "## Project Context\n" + rawContext + "\n\n## Task\n" + task
}

func (s *Store) GetPlan(id string) (string, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.loadPlanLocked(id)
}

func (s *Store) SetPlan(id, plan string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	return os.WriteFile(s.planPath(id), []byte(plan), 0644)
}

// SetPlanGraph persists the typed execution plan graph (plan.Graph JSON) for
// a project — the machine-readable source of truth alongside the rendered
// plan.md/workflow.md caches. Stored raw so this package doesn't depend on
// the plan package.
func (s *Store) SetPlanGraph(id string, data []byte) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	return os.WriteFile(s.graphPath(id), data, 0644)
}

// GetPlanGraph loads the persisted plan graph JSON. Returns os.ErrNotExist
// (wrapped) when the project has no graph yet.
func (s *Store) GetPlanGraph(id string) ([]byte, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return os.ReadFile(s.graphPath(id))
}

// GetWorkflow returns the workflow as markdown, rendered from the structured
// store (workflow.json), migrating a legacy workflow.md project on first
// read. Takes the full lock, not RLock, because that migration can write.
func (s *Store) GetWorkflow(id string) (string, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	wf, err := s.loadWorkflowStructLocked(id)
	if err != nil {
		return "", err
	}
	return RenderWorkflowMarkdown(wf), nil
}

// SetWorkflow parses markdown into the structured model and persists that —
// workflow.json is the canonical store from here on, workflow.md is read
// only as a one-time migration source for projects that predate it.
func (s *Store) SetWorkflow(id, workflow string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.saveWorkflowStructLocked(id, ParseWorkflowMarkdown(workflow))
}

// TaskStatus is a workflow checklist task's state — the local-first upgrade
// plan's "task list with one line how this is being approached," where each
// task carries a stable ID (T1, T2, …) shared with the plan's Mermaid graph
// node IDs so the architecture diagram can render real-time status
// (see server.injectNodeStatus).
type TaskStatus string

const (
	TaskPending TaskStatus = "pending" // "- [ ] T1: ..."
	TaskRunning TaskStatus = "running" // "- [/] T1: ..."
	TaskDone    TaskStatus = "done"    // "- [x] T1: ..."
)

// taskLineRe matches one workflow checklist line in the "- [ ] T1: text"
// format (any of the three checkbox states), capturing the leading
// whitespace+dash, the checkbox state, the space(s) before the ID, the task
// ID itself, and the rest of the line — so MarkTaskStatus can rewrite just
// the checkbox character and leave everything else byte-for-byte identical.
var taskLineRe = regexp.MustCompile(`^(\s*-\s*)\[([ x/])\](\s*)([A-Za-z0-9_-]+):(.*)$`)

// WorkflowTask is one task in a project's standing workflow checklist — the
// structured counterpart of a "- [ ] T1: ..." line. ID is shared with the
// implementation plan's Mermaid graph node IDs (see
// server.injectNodeStatus / planwork.InjectNodeStatus), so status here
// drives the architecture diagram's coloring too.
type WorkflowTask struct {
	ID     string     `json:"id"`
	Title  string     `json:"title"`
	Status TaskStatus `json:"status"`
	Deps   []string   `json:"deps,omitempty"`
}

// Workflow is a project's task checklist as data rather than markdown text.
// Notes holds every line of the source markdown that isn't a checklist item
// (headings, "_Status: ..._" lines, free prose) so migrating an existing
// workflow.md never drops content — it just stops being interleaved with the
// tasks. Rendered back out, Notes comes first and the tasks follow, so a
// workflow that had prose after its checklist will read differently after
// migration even though nothing was deleted.
type Workflow struct {
	Tasks []WorkflowTask `json:"tasks"`
	Notes string         `json:"notes,omitempty"`
}

// ParseWorkflowMarkdown is the markdown→struct half of the workflow model.
// It is also the one-time migration path for a project whose workflow still
// lives only as workflow.md: reusing taskLineRe (the same pattern
// MarkTaskStatus always rewrote by hand) means a workflow written before this
// type existed parses exactly as it always behaved.
func ParseWorkflowMarkdown(md string) Workflow {
	var wf Workflow
	var notes []string
	for _, line := range strings.Split(md, "\n") {
		m := taskLineRe.FindStringSubmatch(line)
		if m == nil {
			notes = append(notes, line)
			continue
		}
		status := TaskPending
		switch m[2] {
		case "x":
			status = TaskDone
		case "/":
			status = TaskRunning
		}
		wf.Tasks = append(wf.Tasks, WorkflowTask{ID: m[4], Title: strings.TrimSpace(m[5]), Status: status})
	}
	wf.Notes = strings.Join(notes, "\n")
	return wf
}

// RenderWorkflowMarkdown is the struct→markdown half, used both to answer
// every caller that still wants workflow text (GetWorkflow, the CLI's
// /workflow, planwork.Amend's prompt) and to re-feed Amend's own markdown
// response back through ParseWorkflowMarkdown before it is persisted.
func RenderWorkflowMarkdown(wf Workflow) string {
	var b strings.Builder
	notes := strings.TrimRight(wf.Notes, "\n")
	if notes != "" {
		b.WriteString(notes)
		b.WriteString("\n")
		if len(wf.Tasks) > 0 {
			b.WriteString("\n")
		}
	}
	for _, t := range wf.Tasks {
		mark := " "
		switch t.Status {
		case TaskDone:
			mark = "x"
		case TaskRunning:
			mark = "/"
		}
		b.WriteString("- [" + mark + "] " + t.ID + ": " + t.Title + "\n")
	}
	return b.String()
}

// loadWorkflowStructLocked loads the structured workflow, migrating from the
// legacy workflow.md checklist (parsed, then persisted as workflow.json) the
// first time a project without one is read. Migration only ever runs once
// per project: every later read hits workflow.json directly.
func (s *Store) loadWorkflowStructLocked(id string) (Workflow, error) {
	data, err := os.ReadFile(s.workflowJSONPath(id))
	if err == nil {
		var wf Workflow
		if json.Unmarshal(data, &wf) == nil {
			return wf, nil
		}
	} else if !os.IsNotExist(err) {
		return Workflow{}, err
	}

	md, err := s.loadWorkflowLocked(id)
	if err != nil {
		return Workflow{}, err
	}
	wf := ParseWorkflowMarkdown(md)
	if md != "" {
		if data, merr := json.MarshalIndent(wf, "", "  "); merr == nil {
			_ = os.WriteFile(s.workflowJSONPath(id), data, 0644)
		}
	}
	return wf, nil
}

func (s *Store) saveWorkflowStructLocked(id string, wf Workflow) error {
	data, err := json.MarshalIndent(wf, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(s.workflowJSONPath(id), data, 0644)
}

// GetWorkflowStruct is the structured counterpart of GetWorkflow — for
// callers (the GUI's workflow endpoint) that want the task list as data
// rather than a markdown document to re-parse.
func (s *Store) GetWorkflowStruct(id string) (Workflow, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.loadWorkflowStructLocked(id)
}

// MarkTaskStatus sets the status of the workflow task whose ID matches
// taskID (exact match, e.g. "T3") and persists the change. A no-op (returns
// nil, not an error) if the workflow has no task with that ID — callers
// resolving a task ID from a possibly-stale workflow snapshot shouldn't
// treat a miss as a failure, just nothing to update.
func (s *Store) MarkTaskStatus(id, taskID string, status TaskStatus) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	wf, err := s.loadWorkflowStructLocked(id)
	if err != nil {
		return err
	}
	changed := false
	for i := range wf.Tasks {
		if wf.Tasks[i].ID == taskID {
			wf.Tasks[i].Status = status
			changed = true
			break
		}
	}
	if !changed {
		return nil
	}
	return s.saveWorkflowStructLocked(id, wf)
}

// EnsurePlanSeeded writes a skeleton plan for the project only if no plan
// exists yet (idempotent). Returns the plan that is now in place (the newly
// seeded skeleton, or the existing plan if one was already present). This is
// the root-cause fix for the empty "Implementation Plan" tab: previously a
// freshly created/opened project had no plan until the first chat exchange,
// so the GUI showed "Awaiting plan generation…" indefinitely.
func (s *Store) EnsurePlanSeeded(id, skeleton string) (string, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	existing, err := s.loadPlanLocked(id)
	if err == nil && strings.TrimSpace(existing) != "" {
		return existing, nil
	}
	if strings.TrimSpace(skeleton) == "" {
		skeleton = defaultPlanSkeleton
	}
	if err := os.WriteFile(s.planPath(id), []byte(skeleton), 0644); err != nil {
		return "", err
	}
	return skeleton, nil
}

// EnsureWorkflowSeeded is the workflow counterpart of EnsurePlanSeeded.
func (s *Store) EnsureWorkflowSeeded(id, skeleton string) (string, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	existing, err := s.loadWorkflowStructLocked(id)
	if err == nil && strings.TrimSpace(RenderWorkflowMarkdown(existing)) != "" {
		return RenderWorkflowMarkdown(existing), nil
	}
	if strings.TrimSpace(skeleton) == "" {
		skeleton = defaultWorkflowSkeleton
	}
	if err := s.saveWorkflowStructLocked(id, ParseWorkflowMarkdown(skeleton)); err != nil {
		return "", err
	}
	return skeleton, nil
}

const defaultPlanSkeleton = `# Implementation Plan

_Status: awaiting first task_

## Objective
_Describe the project goal here._

## Architecture
` + "```mermaid" + `
graph TD
  T1[First task]
` + "```" + `

## Milestones
- [ ] _Milestone 1_
- [ ] _Milestone 2_

## Open Questions
- _None yet._
`

// defaultWorkflowSkeleton seeds a single pending task (T1) whose ID matches
// the Mermaid placeholder node in defaultPlanSkeleton, so the T<n> ID
// convention — and therefore server.injectNodeStatus's status-linked
// flowgraph — works from project creation, not only after the first LLM
// rewrite.
const defaultWorkflowSkeleton = `# Workflow Architecture

_Status: awaiting first task_

## Tasks
- [ ] T1: _Describe the first task's approach here._
`

// Touch updates the LastOpened timestamp for a project.
func (s *Store) Touch(id string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	p, err := s.loadMetaLocked(id)
	if err != nil {
		return err
	}
	p.LastOpened = time.Now()
	return s.saveMetaLocked(p)
}

// Delete removes a project and its context.
func (s *Store) Delete(id string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	dir := s.dir(id)
	if _, err := os.Stat(dir); os.IsNotExist(err) {
		return fmt.Errorf("project not found: %s", id)
	}
	return os.RemoveAll(dir)
}

// --- internal helpers (must be called with the appropriate lock held) ---

func (s *Store) dir(id string) string { return filepath.Join(s.root, safeSegment(id)) }

// safeSegment reduces a project id to a single path component, so no id can
// address anything outside the store root.
//
// Ids that this package MAKES are safe: newID emits slug + "-" + six hex, and
// slugify's charset is [a-z0-9-] with no separator in it. Ids it RECEIVES were
// not checked at all, and they arrive from outside — /api/chat takes
// req.Project straight from the request body and hands it to Get, GetPlan and
// GetWorkflow, each of which reaches dir() below. filepath.Join collapses "..",
// so an id of "../../../../etc" resolved to /etc and SetContext would have
// written its context.md there. CodeQL flagged fifteen sinks in this file for
// exactly that reason.
//
// Cleaning against "/" first means the traversal is resolved and then discarded
// rather than trusted: "../../etc/passwd" becomes "/etc/passwd" becomes
// "passwd", a harmless name inside the root. A legitimate id has no separator
// and comes back unchanged.
func safeSegment(id string) string {
	seg := filepath.Base(filepath.Clean("/" + id))
	if seg == "/" || seg == "." || seg == ".." || seg == string(filepath.Separator) {
		// No usable name. Return something that cannot collide with a real
		// project so the caller's ReadFile fails as "not found" rather than
		// landing on the store root itself.
		return "invalid-project-id"
	}
	return seg
}
func (s *Store) metaPath(id string) string       { return filepath.Join(s.dir(id), "project.json") }
func (s *Store) contextPath(id string) string    { return filepath.Join(s.dir(id), "context.md") }
func (s *Store) rawContextPath(id string) string { return filepath.Join(s.dir(id), "context_raw.md") }
func (s *Store) planPath(id string) string       { return filepath.Join(s.dir(id), "plan.md") }
func (s *Store) workflowPath(id string) string   { return filepath.Join(s.dir(id), "workflow.md") }
func (s *Store) workflowJSONPath(id string) string {
	return filepath.Join(s.dir(id), "workflow.json")
}
func (s *Store) graphPath(id string) string   { return filepath.Join(s.dir(id), "graph.json") }
func (s *Store) summaryPath(id string) string { return filepath.Join(s.dir(id), "summary.md") }

func (s *Store) saveMetaLocked(p *Project) error {
	// Never persist the large bodies inside project.json — they live in their
	// own files. Marshal a shallow copy with the bodies cleared. SummaryLen is
	// metadata (small) and IS persisted so staleness survives restarts.
	copy := *p
	copy.Context = ""
	copy.Plan = ""
	copy.Workflow = ""
	copy.Summary = ""
	data, err := json.MarshalIndent(&copy, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(s.metaPath(p.ID), data, 0644)
}

func (s *Store) loadMetaLocked(id string) (*Project, error) {
	data, err := os.ReadFile(s.metaPath(id))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("project not found: %s", id)
		}
		return nil, err
	}
	var p Project
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("parse project %s: %w", id, err)
	}
	p.Context = "" // metadata only
	p.Plan = ""
	p.Workflow = ""
	p.Summary = ""
	return &p, nil
}

func (s *Store) loadContextLocked(id string) (string, error) {
	data, err := os.ReadFile(s.contextPath(id))
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil // no context yet — not an error
		}
		return "", err
	}
	return string(data), nil
}

func (s *Store) loadSummaryLocked(id string) (string, error) {
	data, err := os.ReadFile(s.summaryPath(id))
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil // no summary yet — not an error
		}
		return "", err
	}
	return string(data), nil
}

func (s *Store) loadPlanLocked(id string) (string, error) {
	data, err := os.ReadFile(s.planPath(id))
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}

func (s *Store) loadWorkflowLocked(id string) (string, error) {
	data, err := os.ReadFile(s.workflowPath(id))
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}

// newID builds a slug from the name plus a short random suffix so two projects
// with the same name never collide.
func newID(name string) string {
	slug := slugify(name)
	if len(slug) > 40 {
		slug = slug[:40]
	}
	b := make([]byte, 3)
	_, _ = rand.Read(b)
	return slug + "-" + hex.EncodeToString(b)
}

func slugify(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == ' ' || r == '_' || r == '-':
			b.WriteRune('-')
		}
	}
	out := b.String()
	for strings.Contains(out, "--") {
		out = strings.ReplaceAll(out, "--", "-")
	}
	out = strings.Trim(out, "-")
	if out == "" {
		out = "project"
	}
	return out
}

func cleanTags(tags []string) []string {
	seen := make(map[string]bool)
	var out []string
	for _, t := range tags {
		t = strings.TrimSpace(strings.ToLower(t))
		if t == "" || seen[t] {
			continue
		}
		seen[t] = true
		out = append(out, t)
	}
	return out
}
